[build]
  command = "npm run build"
  publish = ".next"
  functions = "../../netlify/functions"

[dev]
  framework = "next"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  functions = "../../netlify/functions"